### PR TITLE
HELP -- Random forest

### PR DESCRIPTION
**Pull request by CoryMcCartan**
Not only is mSE (similar to variance) very high for the tree, the variable importance only works for whatever variable is stored in index `0`.  Any ideas why?

While individual random trees did a great job on the test data, the random forest (which after all is just averaging 100 random trees) is preforming very badly.

Data generation:

``` java
int n = 200;
DataPoint[] data = new DataPoint[n];
String[] inputKeys = {"A", "B"};
String[] outputKeys = {"Z"};
double[] minimums = {0, 0};
double[] maximums = {100, 100};
for (int i = 0; i < n; i++) {
    double randA = Math.round(Math.random() * 100);
    double randB = Math.round(Math.random() * 100);
    double[] input = {randA, randB};
    double[] output = {(randA > randB) ? 20 : -5};
    data[i] = new DataPoint(inputKeys, input, outputKeys, output);
}
```

(Basically just creates two random numbers and if 1st one is bigger than second one outputs `20`, otherwise outputs `-5`).

@MaxNotarangelo 
@MaxOrth 

Issue #21

### CODE REVIEW

**Comment by bluebuiy** [comment]
It is doing it 200 times, by what n is set to. probably not the problem.
How are you averaging the output of the trees?
How is the importance getting used? I dont see anything with importance.
What are the minimums and maximums doing?

**Comment by CoryMcCartan** [comment]
the code example was just to show what kind of data is being fed into the forest.  there is no problem there.

the problem arises when variable importance is calculated in `RandomForestQEstimator.java`:

``` java
        double[] variableImportance = zeros(variableSize);
        for (int i = 0; i < numberOfTrees; i++) { // each sample
            int oobCount = 0;
            double sum = 0.0;
            // use OOB data to find MSE
            for (int j = 0; j < sampleSize; j++) {
                if (samples[i].used[j]) { // data used in training
                    continue;
                }
                oobCount++;
                DataPoint example = data[j];
                double actual = run(example.getInputs());
                double expected = example.getOutputs()[0];
                sum += Math.pow(actual - expected, 2);
            }
            double treeMSE = sum / oobCount;

            // randomly change variables to get MSE for each variable
            double[] variableMSE = new double[variableSize];
            for (int j = 0; j < variableSize; j++) { // each variable
                sum = 0.0;
                for (int k = 0; k < sampleSize; k++) { // each data point
                    if (samples[i].used[k] == true) { // data used in training
                        continue;
                    }
                    DataPoint example = data[k];
                    double[] inputs = example.getInputs().clone();
                    // randomly change the variable
                    inputs[j] = (maximums[j] - minimums[j]) * Math.random() + minimums[j];
                    double actual = run(inputs);
                    double expected = example.getOutputs()[0];
                    sum += Math.pow(actual - expected, 2);
                }
                variableMSE[j] = sum / oobCount;
            }

            // calculate variable importance based on MSE difference
            for (int j = 0; j < variableSize; j++) {
                variableImportance[j] += variableMSE[j] - treeMSE;
            }
        }

        for (int i = 0; i < variableSize; i++) {
            variableImportance[i] /= numberOfTrees;
        }

        return variableImportance;
```

the `treeMSE` variable ends up with the same value as `variableMSE` at indices above 0.  So variable imporance is 0.  This is odd, because variable values are changed randomly when `variableMSE` is calculated, which should return different ouput than non-randomized values.  This expected behavior only works for `j = 0`.  Why?  What changes between `j = 0` and `j = 1`????

**Comment by CoryMcCartan** [comment]
`minimums` and `maximums` are for input into the forest, which is then inputted into each tree, which is then inputted into the minimizers in order to allow for random values to be generated in a specific range.  Variable importance is calculated inside the forest class.

**Comment by bluebuiy** [comment]
right away I see this:

``` java
double treeMSE = sum / oobCount;
```

where sum is a double and oobCount is an int.  Possible conversion at the wrong time, so the double is getting truncated. I would cast the int to double before anything, like this:

``` java
double treeMSE = sum / ((double)oobCount));
```

**Comment by bluebuiy** [comment]
Is `variableSize` what you think it is? Maby it is not the correct size.
Is

``` java
samples[i].used[j] == true
```

where i > 0 || j > 0?

**Comment by bluebuiy** [comment]
You are only using the first value in 

``` java
double expected = example.getOutputs()[0];
```

**Comment by CoryMcCartan** [comment]
Thanks. Will fix and test.

**Comment by CoryMcCartan** [comment]
This means first output value, not input variable.  There is only one ouput
variable.

**Comment by CoryMcCartan** [comment]
Seeing as I will no longer be working on this, most of the code will likely be rewritten/reworked/deleted, I thought I'd close the issue.

**Pull request closed without merging**
